config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get 'users/signup', :to => 'users#sign_up'
  post 'users/signup', :to => 'users#create_user'
  get 'users/login', :to => 'users#login_page'
  post 'users/login', :to => 'users#login_user'
  delete 'users/login', :to => 'users#logout'


  resources :bands, only: [ :index, :show ] do
    resources :albums, only: [:show, :create, :new]
  end


  get 'band/add', :to => 'bands#add_page'
  post 'band/add', :to => 'bands#add_band'


end

app/models/User.rb
class User < ActiveRecord::Base
  validates :email, :presence => true, :uniqueness => true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validate :password_cannot_be_blank
  attr_accessor :password

  def self.new_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def update_session_token!(token)
    self.update!(session_token: token)
  end

  










private

  def password_cannot_be_blank
    if !self.password.nil? && self.password.length ==0
      errors.add(:password, "cannot be blank")
    end
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :band_id, :presence => true
  validates :title, :presence => true

  belongs_to(
    :band,
    :class_name => "Band",
    :foreign_key => :band_id,
    :primary_key => :id
  )

  has_many(
    :tracks,
    :class_name => "Track",
    :foreign_key => :album_id,
    :primary_key => :id,
    :dependent => :destroy
  )

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true

  has_many(
  :albums,
  :class_name => "Album",
  :foreign_key => :band_id,
  :primary_key => :id,
  :dependent => :destroy
  )



end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :album_id, :presence => true

  belongs_to(
    :album,
    :class_name => "Album",
    :foreign_key => :album_id,
    :primary_key => :id

  )
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @album = Album.new(band_id: params[:band_id])
    render :new
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  def logged_in?
    return false if session[:session_token].nil?
    !!current_user
  end

  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def redirect_loggedin
    redirect_to root_url if logged_in?
  end

  def require_login
    redirect_to root_url if !logged_in?
  end



end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_login

   # impled index

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def add_page
    @band = Band.new
    render :add_page
  end

  def add_band
    @band = Band.new(params[:band].permit(:name))
    if @band.save
      @errors = ["save succesful"]
      render :index
    else
      @errors = @band.errors.full_messages
      render :add_page
    end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_loggedin, only:[:login_page, :sign_up]

  #implied  [:index, :login_page, :sign_up].map{|x| define_method(x){}}

  def create_user
    a = User.new(params.require(:user).permit(:email))
    a.password_digest=BCrypt::Password.create(params[:user][:password])
    if a.save
      a.update_session_token!(logon)
      redirect_to root_url
    else
      @errors = a.errors.full_messages
      render :sign_up
    end
  end

  def login_user
    user = User.find_by_email(params[:user][:email])
    if user.nil?
      @errors=["This email is available!"]
      render :login_page
    elsif !BCrypt::Password.new(user.password_digest).is_password?(params[:user][:password])
      @errors=["Email/password combo is incorrect"]
      render :login_page
    else
      user.update_session_token!(logon)
      redirect_to root_url
    end
  end

  def logout
    session[:session_token] = nil
    redirect_to root_url
  end


  private
  def logon
    token = User.new_session_token
    session[:session_token] = token
    token
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/new.html.erb
<%= render "shared/home_and_error" %>

<% band = @album.band.name %>
<h1>
Add <%='aeiouAEIOU'.include?(band[0]) ? 'an' : 'a'%> <%=band%> album!
</h1>

app/views/albums/show.html.erb
<%= render "shared/home_and_error" %>

<h1> Songs on <%= @album.title %> </h1>
<h2>
<ol>
  <% @album.tracks.each do |track| %>
<li> <a href="<%=root_url%>"> <%=track.title%> </a>
</li>
  <%end %>
</ol>
<h2>

app/views/bands/add_page.html.erb
<%= render "shared/home_and_error" %>


<h1> Add a Band! </h1>

<form  action="<%=band_add_url%>" method="post">
  <label for="band_name">Name of Band</label><br>
  <input name="band[name]" type="text" value='<%=@band.name%>' id= "band_name">

  <input type="submit" value="Add Band">

</form>

app/views/bands/index.html.erb
<%= render "shared/home_and_error" %>

<h1> All our bands </h1>
<h2>
<ol>
  <% Band.all.each do |band| %>
<li> <a href="<%=band_url(band.id)%>"> <%=band.name%> </a> </li>
  <%end %>
</ol>
</h2>



band not here? <a href="<%=band_add_url%>"> add it!<a>

app/views/bands/show.html.erb
<%= render "shared/home_and_error" %>

<h1> All albums available for <%= @band.name %> </h1>
<h2>
<ol>
  <% @band.albums.each do |album| %>
<li> <a href="<%=band_album_url(band_id: @band.id, id: album.id)%>"> <%=album.title%> </a>
</li>
  <%end %>
</ol>
</h2>


Album not here? <a href="<%=new_band_album_url(:band_id => @band.id)%>"> add it!<a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_home_and_error.html.erb
<a href="<%=root_url%>"> Home </a> </li>
<br>
<ul>
<% while !@errors.to_a.empty? %>
  <li><%=@errors.pop %></li>
  <%end %>
</ul>

app/views/users/index.html.erb
<h1>Hey! Welcome to my music app<h1>
<%if !logged_in? %>
  <a href="<%=users_signup_url%>"> Sign Up!</a>
  <br><br>
  <a href="<%=users_login_url %>">Log in</a>
<%else %>
  <h2> signed in as <%=current_user.email %></h2>
    <form action="<%=users_login_url%>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Logout">
    <form><br><br>
    <a href="<%=bands_url%>"> Go to bands! </a>
<%end %>

app/views/users/login_page.html.erb
<%= render "shared/home_and_error" %>


<h1> Login </h1>

  <form action="<%=users_login_url%>" method="POST">
  <p1>email<p1>
  <input type="text" name="user[email]" >
  <br>
  <p1>password</p1>
  <input type="password" name="user[password]">
  <br>
  <input type="submit" value="Submit">
  <form>
  <br>
  <br>
  <li> Not a member? </li>
  <li> <a href="<%=users_signup_url%>"> Sign Up!</a> </li>

app/views/users/sign_up.html.erb
<%= render "shared/home_and_error" %>

<h1> Sign Up! </h1>



<form action="<%=users_signup_url%>" method="POST">
<p1>email<p1>
<input type="text" name="user[email]" >
<br>
<p1>password</p1>
<input type="password" name="user[password]">
<br>
<input type="submit" value="Submit">
<form>
<br><br>
<li> Already a member? </li>
<li> <a href="<%=users_login_url%>"> Sign In!</a> </li>